import { RootLayout } from '@/components/layouts/RootLayout'
import { RootLayoutProps } from '@/components/layouts/RootLayout/interfaces'

export const metadata = {
  title: 'Next Starter Template',
  description: 'Generated by ggp-next-starter-template',
}

export default function Component({ children }: RootLayoutProps) {
  return <RootLayout>{children}</RootLayout>
}
